GET http://34.67.98.110:3001
Authorization: Bearer YOUR_TOKEN

### Login Route
POST http://34.67.98.110:3001/auth/login?api_key=YOUR_API_KEY
Content-Type: application/json

{
    "username": "farismnrr",
    "email": "test@gmail.com",
    "password": "root1a231231"
}

### Register Route
POST http://34.67.98.110:3001/auth/register?api_key=YOUR_API_KEY
Content-Type: application/json

{
    "username": "farismnrrr",
    "email": "testr@gmail.com",
    "password": "root1a231231"
}

### Refresh Token Route
POST http://34.67.98.110:3001/auth/refresh-token?api_key=YOUR_API_KEY
Content-Type: application/json

{
    "refreshToken": "YOUR_REFRESH_TOKEN"
}

### Logout Route
DELETE http://34.67.98.110:3001/auth/logout?api_key=YOUR_API_KEY
Content-Type: application/json

{
    "refreshToken": "YOUR_REFRESH_TOKEN"
}
