const express = require('express');
const router = express.Router();
const {
    beras-putih,
    beras-merah,
    beras-hitam,
    beras-ketan,
    jagung,
    jelai,
    milet,
    oatmeal,
    quinoa,
    soba,
} = require('../handler/handler-biji');

const {
    apel,
    pisang,
    alpukat,
    kiwi,
    pepaya,
    jambu-biji,
    buah-naga,
    mangga,
    pir,
    labu-kuning,
    melon,
    buah-plum,
    buah-bit,
} = require('../handler/handler-buah');

const {
    jahe,
    kunyit,
    kayu-manis,
    ketumbar,
    daun-salam,
    daun-jeruk,
    oregano,
    bawang-bombay,
    bawang-putih,
    bawang-merah,
} = require('../handler/handler-bumbu');

const {
    daging-sapi,
    daging-kambing,
    daging-ayam,
    daging-bebek,
    daging-domba,
    telur,
} = require('../handler/handler-daging-protein');

const {
    almond,
    biji-aprikot,
    biji-labu,
    hazelnut,
    kacang-tanah,
    kacang-hijau,
    kacang-hitam,
    kacang-kedelai,
    kacang-koro,
    kacang-mede,
    kacang-merah,
    kacang-pecan,
    kacang-pinus,
    kacang-polong,
    kacang-tunggak,
    kacang-kenari,
    kuaci,
    macadamia,
    pistacio,
    tauge,
    edamame,
} = require('../handler/handler-kacang');

const {
    ikan-kembung,
    kerang-hijau,
    abalone,
    kepiting,
    tiram,
    udang,
    cumi,
    gurita,
    lobster,
    sotong,
    rumput-laut,
    ikan-salmon,
    nila,
    ikan-teri,
    ikan-tongkol,
    ikan-dori,
    ikan-bawal,
    ikan-tenggiri,
    belut,
    ikan-gabus,
    ikan-kod,
    lele,
    gurame,
    kakap,
    bandeng,
    tuna,
} = require('../handler/handler-makanan-laut');

const {
    selada,
    akar-teratai,
    arugula,
    asparagus,
    daun-bawang,
    pakcoy,
    brokoli,
    daun-kelor,
    buncis,
    bayam,
    wortel,
    kacang-panjang,
    kangkung,
    kol,
    kembang-kol,
    labu-putih,
    labu-siam,
    oyong,
    paprika,
    sawi-hijau,
    kentang,
    seledri,
    terong,
    mentimun,
    tomat,
    jamur-tiram,
    jamur-shiitake,
    jamur-enoki,
    jamur-champignon,
} = require('../handler/handler-sayur');

router.get('/all-foods', (req, res) => {
    const allFoods = {
        biji: {
            beras-putih,
            beras-merah,
            beras-hitam,
            beras-ketan,
            jagung,
            jelai,
            milet,
            oatmeal,
            quinoa,
            soba,
        },
        buah: {
            apel,
            pisang,
            alpukat,
            kiwi,
            pepaya,
            jambu-biji,
            buah-naga,
            mangga,
            pir,
            labu-kuning,
            melon,
            buah-plum,
            buah-bit,
        },
        bumbu: {
            jahe,
            kunyit,
            kayu-manis,
            ketumbar,
            daun-salam,
            daun-jeruk,
            oregano,
            bawang-bombay,
            bawang-putih,
            bawang-merah,
        },
        dagingProtein: {
            daging-sapi,
            daging-kambing,
            daging-ayam,
            daging-bebek,
            daging-domba,
            telur,
        },
        kacang: {
            almond,
            biji-aprikot,
            biji-labu,
            hazelnut,
            kacang-tanah,
            kacang-hijau,
            kacang-hitam,
            kacang-kedelai,
            kacang-koro,
            kacang-mede,
            kacang-merah,
            kacang-pecan,
            kacang-pinus,
            kacang-polong,
            kacang-tunggak,
            kacang-kenari,
            kuaci,
            macadamia,
            pistacio,
            tauge,
            edamame,
        },
        makananLaut: {
            ikan-kembung,
            kerang-hijau,
            abalone,
            kepiting,
            tiram,
            udang,
            cumi,
            gurita,
            lobster,
            sotong,
            rumput-laut,
            ikan-salmon,
            nila,
            ikan-teri,
            ikan-tongkol,
            ikan-dori,
            ikan-bawal,
            ikan-tenggiri,
            belut,
            ikan-gabus,
            ikan-kod,
            lele,
            gurame,
            kakap,
            bandeng,
            tuna,
        },
        sayur: {
            selada,
            akar-teratai,
            arugula,
            asparagus,
            daun-bawang,
            pakcoy,
            brokoli,
            daun-kelor,
            buncis,
            bayam,
            wortel,
            kacang-panjang,
            kangkung,
            kol,
            kembang-kol,
            labu-putih,
            labu-siam,
            oyong,
            paprika,
            sawi-hijau,
            kentang,
            seledri,
            terong,
            mentimun,
            tomat,
            jamur-tiram,
            jamur-shiitake,
            jamur-enoki,
            jamur-champignon,
        },
    };

    res.send(allFoods);
});

module.exports = router;
