const express = require('express');
const router = express.Router();
const {
    berasPutih,
    berasMerah,
    berasHitam,
    berasKetan,
    jagung,
    jelai,
    milet,
    oatmeal,
    quinoa,
    soba,
} = require('../handler/handler-biji');

const {
    apel,
    pisang,
    alpukat,
    kiwi,
    pepaya,
    jambuBiji,
    buahNaga,
    mangga,
    pir,
    labuKuning,
    melon,
    buahPlum,
    buahBit,
} = require('../handler/handler-buah');

const {
    Jahe,
    Kunyit,
    KayuManis,
    Ketumbar,
    DaunSalam,
    DaunJeruk,
    Oregano,
    BawangBombay,
    BawangPutih,
    BawangMerah,
} = require('../handler/handler-bumbu');

const {
    dagingSapi,
    dagingKambing,
    dagingAyam,
    dagingBebek,
    dagingDomba,
    telur,
} = require('../handler/handler-daging-protein');

const {
    almond,
    bijiAprikot,
    bijiLabu,
    hazelnut,
    kacangTanah,
    kacangHijau,
    kacangHitam,
    kacangKedelai,
    kacangKoro,
    kacangMede,
    kacangMerah,
    kacangPecan,
    kacangPinus,
    kacangPolong,
    kacangTunggak,
    kacangKenari,
    kuaci,
    macadamia,
    pistacio,
    tauge,
    edamame,
} = require('../handler/handler-kacang');

const {
    ikanKembung,
    kerangHijau,
    abalone,
    kepiting,
    tiram,
    udang,
    cumi,
    gurita,
    lobster,
    sotong,
    rumputLaut,
    ikanSalmon,
    nila,
    ikanTeri,
    ikanTongkol,
    ikanDori,
    ikanBawal,
    ikanTenggiri,
    belut,
    ikanGabus,
    ikanKod,
    lele,
    gurame,
    kakap,
    bandeng,
    tuna,
} = require('../handler/handler-makanan-laut');

const {
    selada,
    akarTeratai,
    arugula,
    asparagus,
    daunBawang,
    pakcoy,
    brokoli,
    daunKelor,
    buncis,
    bayam,
    wortel,
    kacangPanjang,
    kangkung,
    kol,
    kembangKol,
    labuPutih,
    labuSiam,
    oyong,
    paprika,
    sawiHijau,
    kentang,
    seledri,
    terong,
    mentimun,
    tomat,
    jamurTiram,
    jamurShiitake,
    jamurEnoki,
    jamurChampignon,
} = require('../handler/handler-sayur');

router.get('/all-foods', (req, res) => {
    const allFoods = {
        biji: {
            berasPutih,
            berasMerah,
            berasHitam,
            berasKetan,
            jagung,
            jelai,
            milet,
            oatmeal,
            quinoa,
            soba,
        },
        buah: {
            apel,
            pisang,
            alpukat,
            kiwi,
            pepaya,
            jambuBiji,
            buahNaga,
            mangga,
            pir,
            labuKuning,
            melon,
            buahPlum,
            buahBit,
        },
        bumbu: {
            Jahe,
            Kunyit,
            KayuManis,
            Ketumbar,
            DaunSalam,
            DaunJeruk,
            Oregano,
            BawangBombay,
            BawangPutih,
            BawangMerah,
        },
        dagingProtein: {
            dagingSapi,
            dagingKambing,
            dagingAyam,
            dagingBebek,
            dagingDomba,
            telur,
        },
        kacang: {
            almond,
            bijiAprikot,
            bijiLabu,
            hazelnut,
            kacangTanah,
            kacangHijau,
            kacangHitam,
            kacangKedelai,
            kacangKoro,
            kacangMede,
            kacangMerah,
            kacangPecan,
            kacangPinus,
            kacangPolong,
            kacangTunggak,
            kacangKenari,
            kuaci,
            macadamia,
            pistacio,
            tauge,
            edamame,
        },
        makananLaut: {
            ikanKembung,
            kerangHijau,
            abalone,
            kepiting,
            tiram,
            udang,
            cumi,
            gurita,
            lobster,
            sotong,
            rumputLaut,
            ikanSalmon,
            nila,
            ikanTeri,
            ikanTongkol,
            ikanDori,
            ikanBawal,
            ikanTenggiri,
            belut,
            ikanGabus,
            ikanKod,
            lele,
            gurame,
            kakap,
            bandeng,
            tuna,
        },
        sayur: {
            selada,
            akarTeratai,
            arugula,
            asparagus,
            daunBawang,
            pakcoy,
            brokoli,
            daunKelor,
            buncis,
            bayam,
            wortel,
            kacangPanjang,
            kangkung,
            kol,
            kembangKol,
            labuPutih,
            labuSiam,
            oyong,
            paprika,
            sawiHijau,
            kentang,
            seledri,
            terong,
            mentimun,
            tomat,
            jamurTiram,
            jamurShiitake,
            jamurEnoki,
            jamurChampignon,
        },
    };

    res.send(allFoods);
});

module.exports = router;

module.exports = router;
